### ISSUE TITLE
Ask for license

### ISSUE THREAD

**Issue by yihong0618** [felixgomez/gitlab-skyline#4]
Hi~

Thank you for your great job.

I maybe kind of use some of your code for my repo, but I notice that your repo doesn't contain `License`, So I don't know I can use or not.

Can I know which  `Open Source License` you use.

Thank you very much.

**Comment by felixgomez** [comment]
Finally I have added the unlicensed license ;)

Thank you very much for your interest in the project!
Use it for whatever you want.

**Comment by yihong0618** [comment]
Thank you very much for you wonderful work~
